// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times_to_random = Integer.parseInt(args[0]);
		int i = 0;
		double ratio = 0;
		double smaller_then_half = 0;
		double larger_then_half = 0;

		while (i < times_to_random) {
			double random = Math.random();
			if (random <= 0.5){
			 smaller_then_half = smaller_then_half + 1;
			}
			if (random > 0.5){
			 larger_then_half = larger_then_half + 1;
			}
			i = i + 1;
		}
		ratio = larger_then_half / smaller_then_half;
		
		System.out.println("> 0.5:" + larger_then_half + " times");
		
		System.out.println("<= 0.5:" + smaller_then_half + " times");
		System.out.println("Ratio: " + ratio);

		
	


	}
}
